blueprints/apartment_manager.py
from datetime import date, datetime

from flask import (
    Blueprint,
    Flask,
    flash,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from sqlalchemy import asc, desc

from db import db
from models import (
    ApartmentModel,
    BillModel,
    BillSettlementModel,
    BillTypeModel,
    CountryModel,
    CurrencyModel,
    MonthlyRentPaymentModel,
    RentalAgreementModel,
    TenantModel,
    UserModel,
    UserPass,
)
from utils import date_utils

apartment_manager = Blueprint("apartment_manager", __name__,template_folder='../templates')


@apartment_manager.route('/apartment-manager/<string:apartment_name>/', defaults={'tab_name':'rental-agreement-tab '} ,methods=['GET','POST'])
@apartment_manager.route('/apartment-manager/<string:apartment_name>/<string:tab_name>', methods=['GET', 'POST'])
def manager(apartment_name, tab_name):


    login = UserPass(user_name=session.get('user'))
    login.get_user_info()
    if not login.is_valid:
        return redirect(url_for('auth.log_in'))
    
    # tab_name = tab_name
    user_model = UserModel.query.filter(UserModel.userName == login.user_name).first()

    current_apartment= ApartmentModel.query.filter(ApartmentModel.apartmentName ==apartment_name, 
                                                    ApartmentModel.userId==user_model.userId).first()
    
    get_all_user_apartments = ApartmentModel.query.filter(ApartmentModel.userId ==user_model.userId ).all()

    get_all_apartment_agreements = RentalAgreementModel.query.filter(RentalAgreementModel.userId ==user_model.userId,
                                                                RentalAgreementModel.apartmentId == current_apartment.apartmentId
                                                                ).order_by(asc(RentalAgreementModel.startDate)).all()
    
    get_apartment_rent_payments = MonthlyRentPaymentModel.query.filter(MonthlyRentPaymentModel.apartmentId == current_apartment.apartmentId
                                                                       ).order_by(asc(MonthlyRentPaymentModel.monthBillingPeriod)).all()
    
    get_all_apartment_bills = BillModel.query.filter(BillModel.apartmentId == current_apartment.apartmentId
                                                     ).order_by(asc(BillModel.monthBillingPeriod)).all()
    
    get_bills_settlements = BillSettlementModel.query.filter(BillSettlementModel.apartmentId ==current_apartment.apartmentId
                                                            ).order_by(BillSettlementModel.monthBillingPeriod).all()
    # print(get_apartment_rent_payments)
    # agreements = None
    
    apartment_name =apartment_name
    
    return render_template('apartment_manager.html',
                            login=login, 
                            active_menu ='apprent_manager',
                            apartment_name= current_apartment, 
                            apartments=get_all_user_apartments,
                            agreements = get_all_apartment_agreements,
                            apartment_rent_payments = get_apartment_rent_payments,
                            apartment_bills = get_all_apartment_bills,
                            bills_settlements = get_bills_settlements,
                            tab_name = tab_name)


# TAB - Rental Agreement
@apartment_manager.route('/new-rental-agreement/<string:apartment_name>', methods=['GET','POST'])
def new_rental_agreement(apartment_name):



    login = UserPass(user_name=session.get('user'))
    login.get_user_info()
    if not login.is_valid:
        return redirect(url_for('auth.log_in'))
    
    user_model = UserModel.query.filter(UserModel.userName == login.user_name).first()
    current_apartment= ApartmentModel.query.filter(ApartmentModel.apartmentName ==apartment_name, 
                                                                ApartmentModel.userId==user_model.userId).first()
    
    get_all_user_apartments = ApartmentModel.query.filter(ApartmentModel.userId ==user_model.userId ).all()
    
    countries_list = CountryModel.query.all()
    currencies_list = CurrencyModel.query.all()

    # data_start_model = RentalAgreementModel.query.filter(RentalAgreementModel.userId==user_model.userId,
    #                                              RentalAgreementModel.apartmentId ==current_apartment.apartmentId
    #                                              ).with_entities(RentalAgreementModel.startDate).all()
    
    # data_start_list = [  data  for data in data_start_model]
    # print(min(data_start_list))

    

    agreement= {}
    

    if request.method=='GET':
        return render_template('new_rental_agreement.html', 
                               login=login, 
                               active_menu ='apprent_manager',
                               countries_list= countries_list,
                               currencies_list= currencies_list,
                               agreement = agreement,
                               apartment = current_apartment,
                               apartments = get_all_user_apartments)
    else:
        
        agreement = {}
        message = None

        agreement_name = request.form.get('agreement_name', '')
        tenant_first_name = request.form.get('tenant_first_name', '')
        tenant_last_name = request.form.get('tenant_last_name', '')
        tenant_phone_number = request.form.get('tenant_phone_number', '')
        tenant_email  = request.form.get('tenant_email', '')
        start_date = request.form.get('start_date', '')
        end_date = request.form.get('end_date', '')
        currency_id = int(request.form.get('currencyId', 4)) # Polish Zloty id for default value
        payment_due_date = request.form.get('payment_due_date', '')
        deposit_amount = request.form.get('deposit_amount', '')
        monthly_rent_payment = request.form.get('monthly_rent_payment', '')
        bills_settlement = request.form.get('bills_settlement')
        monthly_bills_amount = request.form.get('monthly_bills_amount', '')
        additional_information = request.form.get('additional_information', '')

        is_renatl_agreement_name_unique = (RentalAgreementModel.query.filter(RentalAgreementModel.agreementName ==agreement_name, 
                                                                RentalAgreementModel.userId==user_model.userId).count() ==0)


        # Checking the form
        match is_renatl_agreement_name_unique:
            case False:
                message = 'The agreement name must be unique.'
                flash(message)

        match  agreement_name:
            case '':
                message = 'The agreement name cannot be left empty.'
                flash(message)

        match  tenant_first_name:
            case '':
                message = "Tenant's first name cannot be left empty."
                flash(message)

        match  start_date:
            case '':
                message = "Start date name cannot be left empty."
                flash(message)


        match  end_date:
            case '':
                message = "End date name cannot be left empty."
                flash(message)

        match  payment_due_date:
            case '':
                message = "The monthly payment due date cannot be left empty."
                flash(message)

        match  deposit_amount: 
            case '':
                message = "The deposit amount cannot be left empty."
                flash(message)

        match  monthly_rent_payment:
            case '':
                message = "Monthly rent payment cannot be left empty."
                flash(message)

        match (bills_settlement, monthly_bills_amount):
            case ('yes', ''):
                message = "Monthly bills amount cannot be left empty if there is a bills settlement."
                flash(message)
                

        if start_date:
            start_date = date.fromisoformat(start_date)

        if end_date:
            end_date =date.fromisoformat(end_date)

        if not start_date == '' and  not end_date == '':
            if start_date >= end_date:
                message = "The start date must be earlier than the end date."
                flash(message)
            else:
                # Overlapping
                overlapping_agreements = RentalAgreementModel.query.filter(RentalAgreementModel.apartmentId  == current_apartment.apartmentId,
                                                                           RentalAgreementModel.userId==user_model.userId,
                                                                           RentalAgreementModel.startDate <= end_date,
                                                                           RentalAgreementModel.endDate >= start_date).all()
                # print('Overlapping: ', overlapping_agreements)
                if overlapping_agreements:
                    message = "The new rental period overlaps with an existing rental agreement."
                    flash(message)


        match bills_settlement:
            case 'yes':
                bills_settlement = True
            case 'no': 
                bills_settlement = False
                monthly_bills_amount = None

        # START ---- Check
        # request_form_data ={}
        # for key in request.form:
        #     request_form_data[key] = request.form.get(key,'')

        # for key, value in request_form_data.items():
        #     print(key, value)
        # END ---- Check

        if not message:

            # TenantModel
            tenant = TenantModel(tenantFirstName = tenant_first_name,
                                tenantLastName = tenant_last_name,
                                tenantTelephone = tenant_phone_number, 
                                tenantEmail = tenant_email)
            db.session.add(tenant)
            db.session.commit()

blueprints/auth.py
from flask import (
    Blueprint,
    Flask,
    flash,
    redirect,
    render_template,
    request,
    session,
    url_for,
)

from db import db
from models import UserModel, UserPass

auth = Blueprint("auth", __name__,template_folder='../templates')




@auth.route('/signup', methods=['GET','POST'])
def sign_up():

    login = UserPass(user_name=session.get('user'))
    login.get_user_info()

    message = None
    user ={}

    if request.method == 'GET':
        return render_template('signup.html',user=user, login=login)
    else:
        user['first_name'] = '' if not 'first_name' in request.form else request.form['first_name'] 
        user['last_name'] = '' if not 'last_name' in request.form else request.form['last_name'] 
        user['user_name'] = '' if not 'user_name' in request.form else request.form['user_name'] 
        user['user_email'] = '' if not 'user_email' in request.form else request.form['user_email'] 
        user['password'] = '' if not 'password' in request.form else request.form['password'] 
    
        is_user_name_unique = (UserModel.query.filter(UserModel.userName ==user['user_name']).count() ==0)
        is_user_email_unique = (UserModel.query.filter(UserModel.email ==user['user_email']).count() ==0)

        if user['user_name']  == '':
            message = 'Name cannot be emtpy'
        elif user['user_email'] == '':
            message = 'email cannot be emtpy'
        elif user['password'] == '':
            message = 'Password cannot be emtpy'
        elif not is_user_name_unique:
            message = 'User with the User name {} already exists'.format(user['user_name'])
        elif not is_user_email_unique:
            message = 'User with the email {} already exists'.format(user['user_email'])

        
        
        if not message:
            user_pass = UserPass(first_name = user['first_name'],
                                 last_name = user['last_name'],
                                 user_name = user['user_name'],
                                 user_email = user['user_email'],
                                 password =  user['password'])
            
            password_hash = user_pass.hash_password()

            new_user = UserModel(firstName=user['first_name'],
                                lastName=user['last_name'],
                                userName=user['user_name'],
                                email= user['user_email'],
                                password= password_hash,
                                isActive= True,
                                isAdmin = False)
            db.session.add(new_user)
            db.session.commit()
            
            flash('Welcome {} to the AppRent!'.format(user['user_name']))
            flash('You can now log in and manage your rental apartments as the owner.')
            return redirect(url_for('dash.dashboard',login=login ))
        else:
            flash('Correct error: {}.'.format(message))
            login = ''
            return render_template('signup.html',user=user,login=login)



@auth.route('/login', methods=['GET','POST'])
def log_in():

    login = UserPass(user_name=session.get('user'))
    login.get_user_info()

    if request.method == 'GET':
        return render_template('login.html', active_menu='login', login=login)
    else:
        user_name = '' if 'user_name' not in request.form else request.form['user_name']
        password = '' if 'password' not in request.form else request.form['password']

        login = UserPass(user_name = user_name,password = password)
        login_record = login.login_user()

        if login_record != None:
            session['user'] = user_name
            flash('Logon succesfull, welcome {}.'.format(user_name))
            return redirect(url_for('main.index'))
        else:
            flash('Logon failed, try again.')
            return render_template('login.html',active_menu ='login',login=login)
        

        
@auth.route('/logout')
def log_out():
    
    if 'user' in session:
        session.pop('user', None)
        flash('You are logged out.')
    return redirect(url_for('auth.log_in'))

templates/admin_panel.html
{% extends "base.html" %} {% block content %}
<!-- Modal DELET BTN-->
<div
  class="modal fade"
  id="confirmDeleteModal"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">
          This user will be deleted:
        </h1>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body" id="idDeleteModalBody">...</div>
      <div class="modal-footer">
        <form action="" method="GET" id="confirmDeleteForm">
          <button
            type="button"
            class="btn btn-modal-close"
            data-bs-dismiss="modal"
          >
            Close
          </button>
          <button type="submit" class="btn btn-danger">Delete</button>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- Modal DELET BTN-->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script>
  $(document).ready(function () {
    //For a Delete Record Popup
    // This function is applied to all elements with class ending with ".delete-confirm"
    $(".delete-confirm").click(function () {
      //getattributes of the found element
      var desc = $(this).attr("data-desc");
      var url = $(this).attr("data-url");
      //the #... designes id if an element - change the text in the modal window
      $("#idDeleteModalBody").text(desc);
      $("#confirmDeleteForm").attr("action", url);
    });
  });
</script>

<!-- container -->
<div class="container py-5 main-design">
  <div class="row">
    <div class="col-12">
      <div class="info-first title-admin-panel col-4"><p>admin panel</p></div>
      <div class="row">
        <div class="col-10"></div>
        <div class="col-2 add-user">
          <form action="{{url_for('admin.new_user')}}">
            <label for="exampleInputLastName" class="form-label"
              >Add user:</label
            >
            <button type="submit" class="btn btn-add-user">
              <i class="fa-solid fa-user-plus fa-lg i-add-user"></i>
            </button>
          </form>
        </div>
      </div>

      <table class="table table-hover mt-4">
        <thead class="table-dark">
          <tr>
            <th scope="col">User name</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Email</th>
            <th scope="col">Is active</th>
            <th scope="col">Is admin</th>
            <th scope="col">Action</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tr>
          {% for user in users%}
          <th scope="row">{{ user.userName}}</th>

          <td>{{ user.firstName }}</td>
          <td>{{ user.lastName }}</td>
          <td>{{ user.email }}</td>
          <td>
            <a
              href="{{url_for('admin.user_status_chenge', action='active', user_name = user.userName)}}"
            >
              {%if user.isActive %} &check; {%else%} &#x25a2; {% endif %}
            </a>
          </td>

          <td>
            <a
              href="{{url_for('admin.user_status_chenge', action='admin', user_name = user.userName)}}"
            >
              {%if user.isAdmin %} &check; {%else%} &#x25a2; {% endif %}
            </a>
          </td>
          <td>
            <a
              href="{{url_for('admin.edit_user', user_name= user.userName)}} "
              class="btn btn-info btn-sm delete-confirm btn-users-list {{'disabled' if user.userName == login.user_name}}"
              >Edit</a
            >
          </td>
          <td>
            <a
              href="#"
              class="btn btn-danger btn-sm delete-confirm btn-users-list {{'disabled' if user.userName == login.user_name}}"
              data-bs-toggle="modal"
              data-bs-target="#confirmDeleteModal"
              data-desc="{{'Delete user {}?'.format(user.userName)}}"
              data-url="{{url_for('admin.delete_user',user_name= user.userName)}}"
              >Delete</a
            >
          </td>
        </tr>

        {% endfor %}

        <tbody></tbody>
      </table>
    </div>
  </div>
</div>

{% endblock %}

templates/footer.html
<footer class="bg-dark text-light py-3 text-center fixed-bottom">
  <p class="mb-0">&copy; 2024 | AppRent Manager</p>
</footer>

templates/new_rental_agreement.html
{% extends "base.html" %} {% block content %}
<div class="container">
  <div class="index">
    <div class="info-signup">
      <div class="info-first"><p>New rental agreement</p></div>
      <form
        method="POST"
        action="{{url_for('apartment_manager.new_rental_agreement', apartment_name=apartment.apartmentName)}}"
      >
        <div class="mb-3">
          <label for="apartment_name" class="form-label">Apartment Name</label>
          <input
            type="text"
            id="apartment_name"
            name="apartment_name"
            value="{{apartment.apartmentName}}"
            class="form-control"
            readonly
            style="background-color: rgba(13, 110, 253, 0.1)"
          />
        </div>

        <div class="rental-agreement-part-division">
          <div class="mb-3">
            <label for="tenant_first_name" class="form-label"
              ><i class="fa-sharp fa-solid fa-person-to-door"></i>&nbsp;Tenant's
              first name
            </label>
            <input
              type="text"
              id="tenant_first_name"
              name="tenant_first_name"
              value="{{agreement.tenant_first_name}}"
              class="form-control"
              placeholder="Enter tenant's first name"
            />
          </div>
          <div class="mb-3">
            <label for="tenant_last_name" class="form-label"
              >Tenant's last name</label
            >
            <input
              type="text"
              id="tenant_last_name"
              name="tenant_last_name"
              value="{{agreement.tenant_last_name}}"
              class="form-control"
              placeholder="Enter tenant's last name"
            />
          </div>
          <div class="mb-3">
            <label for="tenant_phone_number" class="form-label"
              >Tenant's phone number</label
            >
            <input
              type="tel"
              id="tenant_phone_number"
              name="tenant_phone_number"
              value="{{agreement.tenant_phone_number}}"
              class="form-control"
              placeholder="Enter tenant's phone number"
            />
          </div>
          <div class="mb-3">
            <label for="tenant_email" class="form-label">Tenant's email</label>
            <input
              type="email"
              id="tenant_email"
              name="tenant_email"
              value="{{agreement.tenant_email}}"
              class="form-control"
              placeholder="Enter tenant's email"
            />
          </div>
        </div>
        <div class="mt-3 mb-3 rental-agreement-part-division">
          <div class="mt-3 mb-3">
            <label for="agreement_name" class="form-label"
              ><i class="fa-solid fa-file-signature"></i>&nbsp;Agreement
              Name</label
            >
            <input
              type="text"
              id="agreement_name"
              name="agreement_name"
              value="{{agreement.agreement_name}}"
              class="form-control"
              placeholder="Enter the agreement name"
            />
          </div>
          <div class="row">
            <div class="mb-3 col-6">
              <label for="start_date" class="form-label">Start date</label>
              <input
                type="date"
                id="start_date"
                name="start_date"
                value="{{agreement.start_date}}"
                class="form-control"
              />
            </div>
            <div class="mb-3 col-6">
              <label for="end_date" class="form-label">End date</label>
              <input
                type="date"
                id="end_date"
                name="end_date"
                value="{{agreement.end_date}}"
                class="form-control"
              />
            </div>
          </div>
          <div class="row">
            <div class="mb-3 col-6">
              <label for="currency" class="form-label">Payment currency</label>
              <select name="currencyId" id="currencyId" class="form-select">
                {% for currency in currencies_list%} <option
                value="{{currency.currencyId}}" {% if agreement %} {{'selected'
                if currency.currencyId==agreement.currency_id}} {% else %}
                {{'selected' if currency.currencyId==4}} {% endif %} >
                {{currency.currencySymbol}} {% endfor%}
              </select>
            </div>

            <div class="mb-3 col-6">
              <label for="payment_due_date" class="form-label"
                >Monthly payment due date</label
              >
              <input
                type="number"
                id="payment_due_date"
                name="payment_due_date"
                value="{{agreement.payment_due_date}}"
                class="form-control"
                placeholder="Enter day of the month"
                min="1"
                max="31"
              />
            </div>
          </div>

          <div class="mb-3">
            <label for="deposit_amount" class="form-label"
              >Deposit amount</label
            >
            <input
              type="number"
              id="deposit_amount"
              name="deposit_amount"
              value="{{agreement.deposit_amount}}"
              class="form-control"
              placeholder="Enter the deposit amount"
              step="0.01"
              min="0.01"
            />
          </div>
          <div class="mb-3">
            <label for="monthly_rent_payment" class="form-label mb-0"
              >Monthly rent payment</label
            >
            <div id="emailHelp" class="form-text">
              <p class="">
                In this field, enter the monthly rent payment without including
                the bill settlement. If there is a bill settlement, add the
                amount in the 'Monthly bills amount' field.
              </p>
            </div>
            <input
              type="number"
              id="monthly_rent_payment"
              name="monthly_rent_payment"
              value="{{agreement.monthly_rent_payment}}"
              class="form-control"
              placeholder="Enter the monthly rent payment"
              step="0.01"
              min="0.01"
            />
          </div>

          <div class="rental-agreement-part-division">
            <div class="mb-3">
              <label for="bills_settlement_yes" class="form-label mb-0"
                >Bills Settlement included?</label
              >
              <div id="emailHelp" class="form-text">
                <p class="">
                  If 'Yes' is selected, the tenant will pay a fixed amount for
                  bills each month, while the landlord will cover the actual
                  bill costs. This means that the tenant may either owe
                  additional money or receive a refund depending on actual bill
                  usage compared to the fixed amount paid.
                </p>
              </div>
              <div class="form-check">
                <input class="form-check-input" type="radio"
                name="bills_settlement" id="bills_settlement_yes" value="yes"
                onchange="toggleBillsAmountField()" {% if agreement %} {% if
                agreement.bills_settlement == True%} checked {%endif%} {% else
                %}checked {%endif%} />
                <label class="form-check-label" for="bills_settlement_yes">
                  Yes
                </label>
              </div>
              <div class="form-check">
                <input class="form-check-input" type="radio"
                name="bills_settlement" id="bills_settlement_no" value="no"
                onchange="toggleBillsAmountField()" {% if
                agreement.bills_settlement == False%} checked {%endif%} />
                <label class="form-check-label" for="bills_settlement_no">
                  No
                </label>
              </div>
            </div>
            <div class="mb-3">
              <label for="monthly_bills_amount" class="form-label"
                >Monthly bills amount (a fixed, pre-determined amount)</label
              >
              <input
                type="number"
                id="monthly_bills_amount"
                name="monthly_bills_amount"
                value="{{agreement.monthly_bills_amount}}"
                class="form-control"
                placeholder="Enter the monthly bills amount"
                step="0.01"
                min="0.01"
              />
            </div>
          </div>
          <div class="mt-3 mb-3">
            <label for="additional_information" class="form-label"
              >Additional information</label
            >
            <textarea
              id="additional_information"
              name="additional_information"
              class="form-control"
              placeholder="Enter any additional information"
              rows="3"
            >
{{agreement.additional_information}}</textarea
            >
          </div>
        </div>
        <button type="submit" class="btn btn-dark">Add agreement</button>
        <div class="row-end"></div>
      </form>
    </div>
  </div>
</div>

<script>
  function toggleBillsAmountField() {
    const billsSettlementYes = document.getElementById(
      "bills_settlement_yes"
    ).checked;
    const billsAmountField = document.getElementById("monthly_bills_amount");

    if (billsSettlementYes) {
      billsAmountField.removeAttribute("disabled");
      billsAmountField.placeholder = "Enter the monthly bills amount";
    } else {
      billsAmountField.setAttribute("disabled", "disabled");
      billsAmountField.placeholder = "No Bills Settlement";
      billsAmountField.value = "";
    }
  }

  document.addEventListener("DOMContentLoaded", toggleBillsAmountField);
</script>

{% endblock %}

templates/signup.html
{% extends "base.html" %} {% block content %}
<div class="container">
  <div class="index">
    <div class="info-signup">
      <div class="info-first"><p>Sign Up</p></div>
      <form method="POST" action="{{url_for('auth.sign_up')}}">
        <div class="mb-3">
          <label for="exampleInputFirstName" class="form-label"
            >First Name</label
          >
          <input
            type="text"
            id="first_name"
            name="first_name"
            value="{{user.first_name}}"
            class="form-control"
            id="exampleInputFirstName"
            aria-describedby="firstName"
          />
        </div>
        <div class="mb-3">
          <label for="exampleInputLastName" class="form-label">Last Name</label>
          <input
            type="text"
            id="last_name"
            name="last_name"
            value="{{user.last_name}}"
            class="form-control"
            id="exampleInputLastName"
            aria-describedby="lastName"
          />
        </div>
        <div class="mb-3">
          <label for="exampleInputUsername" class="form-label">Username</label>
          <input
            type="text"
            id="user_name"
            name="user_name"
            value="{{user.user_name}}"
            class="form-control"
            id="exampleInputUsername"
            aria-describedby="Username"
          />
        </div>
        <div class="mb-3">
          <label for="exampleInputUserEmail" class="form-label"
            >Email address</label
          >
          <input
            type="email"
            id="user_email"
            name="user_email"
            value="{{user.user_email}}"
            class="form-control"
            id="exampleInputEmail1"
            aria-describedby="emailHelp"
          />
          <div id="emailHelp" class="form-text">
            We'll never share your email with anyone else.
          </div>
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Password</label>
          <input
            type="password"
            id="password"
            name="password"
            class="form-control"
            id="exampleInputPassword1"
          />
        </div>

        <button type="submit" class="btn btn-dark">Sign up</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}